# Site
repository: juilleratn/juilleratn.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Juillerat Noël
title: Dévellopeur Web et application mobile
email: juilleratnoel@gmail.com
phone: 06 11 38 82 41
website: 8 avenue de Maurin,
        34090 Montpellier
        
# Social links
# twitter_username: @Juilleratnoel
github_username:  juilleratn
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: noh.ell
linkedin_username: noel-juillerat-83120a161
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Bonjour, je m'appelle **Noël** et je suis développeur junior. 
  J'ai travaillé dans un certain nombre de sociétés en acquérant des compétences en matière de **travail d'équipe** et d'**adaptabilité**.
  
  De **nature curieuse**, ma détermination m'a toujours amenée à acquérir de nouvelles compétences et à rencontrer de nouvelles personnes.
  Avec un profil confirmé et des compétences multiples, je suis convaincu par la pertinence des solutions innovantes que je suis capable d'apporter.
  Explorez mon site pour en savoir plus ou contactez-moi directement pour toute question.


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
        « La vie, ce n’est pas d’attendre que les orages passent, c’est d’apprendre à danser sous la pluie »

        *Sénèque*
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
